# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "APP_ENV=dev APP_PORT=8080 ./tmp/main"

[log]
  color = "true"
  level = "debug"

[watch]
  exclude_dir = ["vendor", "tmp", ".git", "node_modules"]
